server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:mysqldb}:${MYSQL_PORT:3306}/course_online"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
#    url: "jdbc:mysql://localhost:3306/course_online"
#    driverClassName: "com.mysql.cj.jdbc.Driver"
#    username: root
#    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

app:
  services:
    profile: http://${PROFILE_HOST:localhost}:8081/profile

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8762/eureka/
  instance:
    prefer-ip-address: true