server:
  port: 8085
  servlet:
    context-path: /payment1

spring:
  application:
    name: payment1-service
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:mysqldb}:${MYSQL_PORT:3306}/course_online"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
        dialect: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP-SERVERS_HOST:localhost}:${SPRING_KAFKA_BOOTSTRAP-SERVERS_PORT:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: -1
      retries: 5
      properties:
        request.timeout.ms: 100
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8762/eureka/
  instance:
    prefer-ip-address: true
payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: RNT2VBPW
    secretKey: GAX12WBRHQQN85YG68LBKYCOMPTCD96L
    returnUrl: http://localhost:8888/api/v1/payment1/any/return-vnpay
    version: 2.1.0
    command: pay
    orderType: other

app:
  services:
    course: http://${COURSE_HOST:localhost}:8082/course
    payment: http://${PAYMENT_HOST:localhost}:8084/payment
    identity: http://${IDENTITY_HOST:localhost}:8080/identity

