server:
  port: 8084
  servlet:
    context-path: /payment
spring:
  application:
    name: payment-service
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:mysqldb}:${MYSQL_PORT:3306}/course_online"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP-SERVERS_HOST:localhost}:${SPRING_KAFKA_BOOTSTRAP-SERVERS_PORT:9092}
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      acks: -1
#      retries: 5
#      properties:
#        request.timeout.ms: 100
#        enable.idempotence: true
#        max.in.flight.requests.per.connection: 5

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8762/eureka/
  instance:
    prefer-ip-address: true

app:
  services:
    course: http://${COURSE_HOST:localhost}:8082/course
    payment1: http://${PAYMENT1_HOST:localhost}:8085/payment1
    identity: http://${IDENTITY_HOST:localhost}:8080/identity