server:
  port: 8762
  servlet:
    context-path: /
spring:
  application:
    name: registry-service

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
