server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  datasource:
#    url: "jdbc:mysql://localhost:3306/course_online"
#    driverClassName: "com.mysql.cj.jdbc.Driver"
#    username: root
#    password: 123456
    url: "jdbc:mysql://${MYSQL_HOST:mysqldb}:${MYSQL_PORT:3306}/course_online"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8762/eureka/
  instance:
    prefer-ip-address: true